pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '6d573de9-8665-44be-8e39-6da42ef658b7', 
                url: 'https://github.com/Somraj2929/Jenkins-Pipelines',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Building Docker Image from python-jenkins-argocd-k8s directory'
                    docker build --no-cache -t somraj29/cicd-e2e:${BUILD_NUMBER} -f python-jenkins-argocd-k8s/Dockerfile python-jenkins-argocd-k8s
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps {
                script {
                    withCredentials([string(credentialsId: 'docker-hub-credentials', variable: 'DOCKER_HUB_PASSWORD')]) {
                        sh '''

                        echo 'Pushing the Docker Image to Docker Hub'
                        docker push somraj29/cicd-e2e:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: '6d573de9-8665-44be-8e39-6da42ef658b7', 
                url: 'https://github.com/Somraj2929/ci-cd-manifests.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '6d573de9-8665-44be-8e39-6da42ef658b7', passwordVariable: 'GIT_TOKEN', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        echo "Current Deploy YAML:"
                        cat deploy.yaml
                        
                        echo "Updating Deployment YAML with build number ${BUILD_NUMBER}"
                        sed -i "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        
                        echo "Updated Deploy YAML:"
                        cat deploy.yaml

                        git config --global user.email "somrajbishnoirock29@gmail.com"
                        git config --global user.name "Jenkins Pipeline"

                        git add deploy.yaml
                        git commit -m "Updated the deploy yaml | Jenkins Pipeline"
                        
                        echo "Pushing changes to GitHub..."
                        git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/Somraj2929/ci-cd-manifests.git HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
